FROM python:3.9

WORKDIR /app

COPY requirements.ui.txt .

RUN pip install --upgrade pip \
 && pip install --no-cache-dir -r requirements.ui.txt

COPY src/ui.py .

EXPOSE 8501

CMD ["streamlit", "run", "ui.py", "--server.port=8501", "--server.address=0.0.0.0"]
